// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadIA.Data;

#nullable disable

namespace SquadIA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SquadIA.Models.HistoricoAnalise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bloqueios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bugs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadTimeMedio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeSquad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumoExecutivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreSaude")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Throughput")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HistoricosAnalise");
                });
#pragma warning restore 612, 618
        }
    }
}
